controllers:
    resource: ../src/Controller/
    type: annotation

morph_view:
    resource: "@MorphViewBundle/Resources/config/routes/routing.xml"

ims_product:
    resource: "@ImsProductBundle/Resources/config/routes/routing.xml"
    prefix: "product"
    name_prefix: "product_"

ims_category:
    resource: "@ImsCategoryBundle/Resources/config/routes/routing.xml"
    prefix: "category"
    name_prefix: "category_"
